spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: customer
    password: customer

    jpa:
      hibernate:
        ddl-auto: update
      open-in-view: false

  server:
    port: 8080