spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customerdb}
    username: ${SPRING_DATASOURCE_USERNAME:customer}
    password: ${SPRING_DATASOURCE_PASSWORD:customer}

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false